name: infixedu
description: A new Flutter project.

publish_to: 'none'

version: 2.0.4+19

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0
  dio: ^4.0.0
  equatable: ^1.2.0
  expandable: ^5.0.1
  file_picker: ^3.0.3
  file_utils: ^0.1.3
  flutter_bloc: ^7.0.0
  cell_calendar: ^0.5.0+1
  flutter_calendar_carousel: ^1.4.10
  flutter_cupertino_date_picker_fork: 1.0.3
  flutter_cupertino_localizations: ^1.0.1
  flutter_local_notifications: ^6.0.0
  flutter_webview_plugin: ^0.3.10+1
  fluttertoast: ^3.1.3
  http: ^0.13.0
  open_file: ^3.2.0
  path_provider: ^2.0.1
  permissions_plugin: ^1.1.4
  rxdart: ^0.26.0
  scoped_model: ^1.0.1
  shared_preferences: 2.0.4
  animated_bottom_navigation_bar: ^0.3.2
#  square_in_app_payments: ^1.3.0
  uuid: ^3.0.0
  shimmer: ^2.0.0-nullsafety.0
  fancy_shimmer_image: ^2.0.0-nullsafety.0
  url_launcher: ^6.0.3
  age: ^0.0.1
  intl: ^0.17.0
  flutter_overlay_loader: ^0.1.1
  flutter_cache_manager: ^3.0.0-nullsafety.1
  timeago: ^3.0.2
  flutter_slidable: ^0.5.7
  font_awesome_flutter: ^9.0.0
  pdf_flutter:
    git: https://github.com/emran92/pdf_flutter
#  pdf_flutter: ^1.1.4
  device_preview: ^0.7.1
  provider: 5.0.0
  cached_network_image: ^3.0.0
  flutter_inappwebview: ^5.3.2
  extended_image: 3.0.0
  ffi: ^1.0.0
  firebase_core: ^1.4.0
  firebase_messaging: ^10.0.4
  flutter_dropdown_alert: ^1.0.1
  edge_alert: ^0.0.1
  flutter_screenutil: ^5.0.0+2
  flutter_widget_from_html: ^0.6.1
  flutter_stripe: ^1.1.0
  stripe_platform_interface: ^1.1.0
  plugin_platform_interface: ^2.0.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.1.8+4

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  ios: true
  image_path: "assets/config/logo_blue.png"

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  image: assets/config/logo_blue.png
  fullscreen: true
  color: "FFFFFF"


flutter:
  uses-material-design: true
  assets:
   - assets/config/
   - assets/images/
   - assets/locale/
   - assets/fonts/

fonts:
  - family: popins
    fonts:
      - asset: fonts/poppins_medium.ttf
        weight: 100
      - asset: fonts/poppins_bold.ttf
        weight: 200
      - asset: fonts/poppins_light.ttf
        weight: 300
      - asset: fonts/poppins_regular.ttf
        weight: 400
      - asset: fonts/poppins_semibold.ttf
        weight: 500
  - family: QuickSand
    fonts: 
      - asset: fonts/Quicksand.ttf
